# Generated by Django 6.0.3 on 2026-03-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoRefrigeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación Exacta')),
                ('marca', models.CharField(max_length=100)),
                ('refrigerante', models.CharField(help_text='Ej: R-410A, R-22', max_length=50)),
                ('voltaje', models.CharField(help_text='Ej: 220V / 110V', max_length=20)),
                ('btu', models.IntegerField(verbose_name='Capacidad (BTU)')),
                ('amperaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amperaje (A)')),
                ('potencia_va', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potencia (VA)')),
                ('potencia_w', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potencia (W)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo de Refrigeración',
                'verbose_name_plural': 'Equipos de Refrigeración',
            },
        ),
    ]
