# Generated by Django 6.0.3 on 2026-06-11 22:32

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiporefrigeracion',
            name='tag_id',
            field=models.CharField(default=inventario.models.generar_codigo_ref, max_length=20, unique=True, verbose_name='Código de Inventario'),
        ),
    ]
