# Generated by Django 6.0.3 on 2026-06-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_equiporefrigeracion_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiporefrigeracion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarca esta casilla en lugar de borrar el equipo para mantener el historial.', verbose_name='Equipo Activo'),
        ),
    ]
