"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pbq8&kps(_x3bgjn4o1#g2vozuoxu=c(acl*3xtuso08jg7xu$'

# SECURITY WARNING: don't run with debug turned on in production!
import os
import dj_database_url

# Si la variable 'RENDER' existe en el sistema, DEBUG será False.
# Si no existe (como en mi laptop), DEBUG será True por defecto.
DEBUG = 'RENDER' not in os.environ

# Configuración dinámica de ALLOWED_HOSTS
if not DEBUG:
    # En la nube: Solo permitimos tu URL de Render
    ALLOWED_HOSTS = ['sistema-mantenimiento-pollo.onrender.com']
else:
    # En mi laptop: Permitimos localhost para desarrollo
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'inventario',
    'mantenimiento',
    'reportes',
    'auditlog'
]

JAZZMIN_SETTINGS = {
    "site_title": "Pollo Premium Admin",
    "site_header": "Industrias Pollo Premium",
    "site_brand": "Mantenimiento 5.8",
    "site_logo": "img/logo-PP.png",  # Ruta dentro de /static/
    "login_logo": "img/logo-PP.png",
    "welcome_sign": "Bienvenido al Sistema de Gestión de Mantenimiento para Equipos de Refrigeración",
    "copyright": "Industrias Pollo Premium 5.8 C.A.",
    "search_model": ["inventario.EquipoRefrigeracion", "mantenimiento.PlanPreventivo"],
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "inventario.EquipoRefrigeracion"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware'
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mantenimiento.context_processors.estadisticas_mantenimiento',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://postgres:david@localhost:5432/db_refrigeracion',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os
from pathlib import Path

STATIC_URL = 'static/'

# Esta línea le dice a Django dónde buscar estáticos en desarrollo
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Esta línea es VITAL para cuando subamos el proyecto a la nube (WhiteNoise)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'usuarios.Usuario'