# Generated by Django 6.0.3 on 2026-03-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0002_alter_planpreventivo_fecha_proximo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateField(auto_now_add=True)),
                ('amperaje_leido', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amperaje Medido (A)')),
                ('presion_alta', models.FloatField(blank=True, null=True, verbose_name='Presión Alta (PSI)')),
                ('presion_baja', models.FloatField(blank=True, null=True, verbose_name='Presión Baja (PSI)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tareas_completadas', models.TextField(help_text='Ej: Limpieza de filtros, lavado de serpentín')),
                ('tecnico_responsable', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.planpreventivo', verbose_name='Equipo en Plan')),
            ],
            options={
                'verbose_name': 'Reporte de Servicio',
                'verbose_name_plural': 'Reportes de Servicio',
            },
        ),
    ]
