# Generated by Django 6.0.3 on 2026-03-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticidad', models.CharField(choices=[('ALTA', 'Alta (Mensual - 30 días)'), ('MEDIA', 'Media (Bimestral - 60 días)'), ('BAJA', 'Baja (Trimestral - 90 días)')], default='MEDIA', max_length=10)),
                ('frecuencia_dias', models.PositiveIntegerField(default=60, help_text='Días entre cada mantenimiento')),
                ('limpieza_filtros', models.BooleanField(default=True, verbose_name='Limpieza de Filtros')),
                ('limpieza_evaporadora', models.BooleanField(default=True, verbose_name='Limpieza de Evaporadora (Split)')),
                ('limpieza_condensadora', models.BooleanField(default=True, verbose_name='Limpieza de Condensadora')),
                ('medicion_amperaje', models.BooleanField(default=True, verbose_name='Medición de Consumo de Corriente')),
                ('revision_refrigerante', models.BooleanField(default=True, verbose_name='Revisión de Presión de Gas')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equiporefrigeracion', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Plan Preventivo',
                'verbose_name_plural': 'Planes Preventivos',
            },
        ),
    ]
