# Generated by Django 6.0.3 on 2026-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpreventivo',
            name='fecha_proximo_mantenimiento',
            field=models.DateField(blank=True, help_text='Se calcula automáticamente', null=True),
        ),
    ]
