# Generated by Django 6.0.3 on 2026-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_planpreventivo_fecha_proximo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpreventivo',
            name='fecha_proximo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='limpieza_condensadora',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='limpieza_evaporadora',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='limpieza_filtros',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='medicion_amperaje',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='revision_refrigerante',
            field=models.BooleanField(default=True),
        ),
    ]
