# Generated by Django 6.0.3 on 2026-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_planpreventivo_fecha_proximo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpreventivo',
            name='revision_electrica',
            field=models.BooleanField(default=True, verbose_name='¿Revisión de Conexiones Eléctricas?'),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='criticidad',
            field=models.CharField(choices=[('ALTA', 'Alta (30 días)'), ('MEDIA', 'Media (60 días)'), ('BAJA', 'Baja (90 días)')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='fecha_proximo_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento (Auto)'),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='frecuencia_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Si se deja vacío, se usará la frecuencia por defecto de la criticidad', null=True),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='limpieza_condensadora',
            field=models.BooleanField(default=True, verbose_name='¿Limpieza de Condensadora?'),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='limpieza_evaporadora',
            field=models.BooleanField(default=True, verbose_name='¿Limpieza de Evaporadora?'),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='limpieza_filtros',
            field=models.BooleanField(default=True, verbose_name='¿Limpieza de Filtros?'),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='medicion_amperaje',
            field=models.BooleanField(default=True, verbose_name='¿Medición de Amperaje?'),
        ),
        migrations.AlterField(
            model_name='planpreventivo',
            name='revision_refrigerante',
            field=models.BooleanField(default=True, verbose_name='¿Revisión de Gas Refrigerante?'),
        ),
    ]
