# Generated by Django 6.0.3 on 2026-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_planpreventivo_revision_electrica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpreventivo',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(default='2026-06-12', verbose_name='Último Mantenimiento'),
            preserve_default=False,
        ),
    ]
